name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Limpar dependências e reinstalar
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install

      - name: Verificar instalação do Cypress
        run: npx cypress verify

      - name: Garantir permissões do Cypress
        run: chmod +x node_modules/.bin/cypress

      - name: Executar testes com Cypress
        run: npm test
        env:
          CI: true
